"""empty message

Revision ID: 3661b3aa28b8
Revises: 
Create Date: 2020-09-28 17:49:05.039694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3661b3aa28b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emal', sa.String(length=191), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emal')
    # ### end Alembic commands ###
