"""empty message

Revision ID: 40f12e774305
Revises: 747898b944a6
Create Date: 2020-09-03 12:20:01.639531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f12e774305'
down_revision = '747898b944a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('exam_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('exam_name', sa.String(length=500), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('login_code', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=191), nullable=False),
    sa.Column('last_name', sa.String(length=191), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('confirm_examiner', sa.String(length=255), nullable=True),
    sa.Column('auth_image', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('examRecordings',
    sa.Column('exam_recording_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('exam_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_ended', sa.DateTime(), nullable=True),
    sa.Column('video_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('exam_recording_id')
    )
    op.create_table('examWarnings',
    sa.Column('warning_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('exam_recording_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('warning_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['exam_recording_id'], ['examRecordings.exam_recording_id'], ),
    sa.PrimaryKeyConstraint('warning_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examWarnings')
    op.drop_table('examRecordings')
    op.drop_table('users')
    op.drop_table('exams')
    # ### end Alembic commands ###
