"""empty message

Revision ID: c7856140f4fa
Revises: cb19f7658f3c
Create Date: 2020-09-09 22:19:47.982826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7856140f4fa'
down_revision = 'cb19f7658f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examWarnings', sa.Column('exam_warning_id', mysql.INTEGER(unsigned=True), nullable=False))
    op.drop_column('examWarnings', 'warning_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examWarnings', sa.Column('warning_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False))
    op.drop_column('examWarnings', 'exam_warning_id')
    # ### end Alembic commands ###
